name: Auto Translate Novel

on:
  schedule:
    - cron: '0 12 * * *' # รันทุกๆ 3 ชั่วโมง (ปรับเวลาตรงเลข 3 ได้)
  workflow_dispatch: # ปุ่มกดรันเองด้วยมือ

permissions:
  contents: write # อนุญาตให้บอทบันทึกไฟล์ last_episode_discord.txt กลับเข้า repo ได้

jobs:
  run-translation-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-genai feedparser requests beautifulsoup4
          pip install cloudscraper

      - name: Run Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          WEBHOOK_NOVEL_1: ${{ secrets.WEBHOOK_NOVEL_1 }}
          WEBHOOK_NOVEL_2: ${{ secrets.WEBHOOK_NOVEL_2 }}
        run: python check_novel.py

      - name: Commit and Push DB
        run: |
          git config --global user.name "Auto Bot"
          git config --global user.email "bot@noreply.github.com"
          git add last_episode_discord.txt
          git commit -m "Update last episode database" || echo "No changes to commit"
          git push
