name: Auto Translate Novel

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
    inputs:
      novel_url:
        description: 'วางลิงก์นิยายที่ต้องการแปลใหม่ทั้งหมด'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install google-genai requests beautifulsoup4 cloudscraper

      - name: Run logic
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          WEBHOOK_NOVEL_1: ${{ secrets.WEBHOOK_NOVEL_1 }}
          TARGET_URL: ${{ github.event.inputs.novel_url }}
        run: python check_novel.py

      - name: Save changes
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          # เพิ่ม novel_list.txt เข้าไปใน git add ด้วย
          git add novels.json history_all.txt novel_list.txt 
          git commit -m "Update translations and novel list [skip ci]" || exit 0
          git pull origin main --rebase
          git push